# Start window index from 1
set -g base-index 1
set -w -g pane-base-index 1

# Pass Escape key to application without delay
# This is used by nvim a lot and the default delay is very annoying
# https://superuser.com/questions/942677/consequences-of-escape-time-0-tmux-setting
set -g escape-time 0

# Set status bar colours
set -g status-style bg=colour240
set -g window-status-current-style fg=colour10

# Reindex windows when one is closed
set -g renumber-windows on

# Enable mouse mode
set -g mouse on

# Enable focus-events
set-option -g focus-events on

# Set alacritty colours
set-option -a terminal-features 'alacritty:RGB'

# Run tmux as non-login shell
set -g default-command "${SHELL}"

# Increase the history limit
set-option -g history-limit 30000

# Set VI mode for key bindings
set -w -g mode-keys vi
set -g status-keys vi

# Add key bindings for previous and next prompt
bind -T copy-mode-vi n send-keys -X next-prompt
bind -T copy-mode-vi p send-keys -X previous-prompt
