# Start window index from 1
set -g base-index 1
setw  -g pane-base-index 1

# Pass Escape key to application without delay
# This is used by nvim a lot and the default delay is very annoying
# https://superuser.com/questions/942677/consequences-of-escape-time-0-tmux-setting
set -g escape-time 0

# Set status bar colours
set -g status-style bg=colour240
set -g window-status-current-style fg=colour10
